version: '3.1'

services:
  node:
    build:
      context: .
      dockerfile: .docker/node-dev.dockerfile
      args:
        - NODE_ENV=development
        - PORT=3000
    # command: node --inspect=0.0.0.0:9229
    ports:
      - "3000:3000"
      - "80:80"
      - "5858:5858"
      - "9229:9229"
    networks:
      - isoNet
    volumes:
      - .:/opt/app
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development

  mongodb-docker:
    build:
      context: .
      dockerfile: .docker/mongo-dev.dockerfile
    ports:
      - '27017:27017'
    networks:
      - isoNet

networks:
  isoNet:
    driver: bridge

volumes:
    notused: